apiVersion: v1
kind: Pod
metadata:
  name: nginx1-dummy
  labels:
    app: myapppod
spec:
  containers:
    - name: nginx
      image: nginx 
      env:
        - name: password
          value: mysecretpassword