apiVersion: v1
kind: Service
metadata: 
  name: myapp-service
  labels:
    tier: frontend
spec:
  type: NodePort
  selector:
    app: myapppod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090